//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res_light {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res_light() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.res_light", typeof(res_light).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;160px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 160 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-174.000000, -4316.000000)&quot;&gt;&lt;g id=&quot;编组-9&quot; transform=&quot;translate(174.000000, 4316.000000)&quot;&gt;&lt;g id=&quot;Feedback/Alert/Light/Default-Success&quot; transform=&quot;translate(0.000000, 56.000000)&quot;&gt;&lt;path d=&quot;M154.87223,0.25 C156.584468,0.25 157.20888,0.419442838 157.835792,0.754718707 C158.443432,1.0796883 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;128px&quot; height=&quot;76px&quot; viewBox=&quot;0 0 128 76&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-190.000000, -3023.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Avatar&quot; transform=&quot;translate(190.000000, 3023.000000)&quot;&gt;&lt;g id=&quot;编组&quot;&gt;&lt;circle id=&quot;椭圆形&quot; fill-opacity=&quot;0.25&quot; fill=&quot;#000000&quot; cx=&quot;16&quot; cy=&quot;16&quot; r=&quot;16&quot;&gt;&lt;/circle&gt;&lt;g transform=&quot;translate(7.187918, 6.671993)&quot; id=&quot;b-link&quot;&gt;&lt;g fill=&quot;#000000&quot;&gt;&lt;path d=&quot;M16.9330 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;125px&quot; height=&quot;56px&quot; viewBox=&quot;0 0 125 56&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-552.000000, -3029.000000)&quot;&gt;&lt;g id=&quot;Badge&quot; transform=&quot;translate(552.000000, 3030.000000)&quot;&gt;&lt;g id=&quot;编组&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#EEEEEE&quot; fill-rule=&quot;nonzero&quot; x=&quot;0&quot; y=&quot;8.5&quot; width=&quot;46&quot; height=&quot;46&quot; rx=&quot;4&quot;&gt;&lt;/rect&gt;&lt;g transform=&quot;translate(36.500000, 0.000000)&quot;&gt;&lt;circle id=&quot;椭圆形&quot; stroke=&quot;#FFFFFF&quot; fill=&quot;#FF4D4F&quot; cx [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 824 140&quot; width=&quot;140&quot; height=&quot;140&quot;&gt;&lt;path fill=&quot;#00D379&quot; transform=&quot;scale(2.28898 2.28898)&quot; d=&quot;M339.392 41.4598C339.527 41.7533 339.61 42.0683 339.532 42.3898C339.275 43.4509 338.056 44.7143 337.139 45.2586C336.176 45.83 335.276 45.9465 334.176 46.0066C330.607 46.2015 326.955 46.0427 323.378 46.0364L304.238 46.043C299.846 46.0458 283.113 46.5331 280.137 45.7741C278.922 45.4643 277.949 44.8901 277.299 43.7926C276.666 42.7243 276.367 41.4617 276.213 4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;149px&quot; height=&quot;22px&quot; viewBox=&quot;0 0 149 22&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-546.000000, -1162.000000)&quot;&gt;&lt;g id=&quot;Breadcrumb&quot; transform=&quot;translate(546.000000, 1162.000000)&quot;&gt;&lt;rect id=&quot;矩形复制-48&quot; fill=&quot;#F5F5F5&quot; fill-rule=&quot;nonzero&quot; x=&quot;0&quot; y=&quot;6&quot; width=&quot;32&quot; height=&quot;10&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-49&quot; fill=&quot;#F5F5F5&quot; fill-rule=&quot;nonzero&quot; x=&quot;59&quot; y=&quot;6&quot; width=&quot;32&quot; height=&quot;10&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Breadcrumb {
            get {
                return ResourceManager.GetString("Breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;80px&quot; height=&quot;111px&quot; viewBox=&quot;0 0 80 111&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-214.000000, -424.000000)&quot;&gt;&lt;g id=&quot;Button&quot; transform=&quot;translate(214.000000, 424.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#1677FF&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;79&quot; height=&quot;31&quot; rx=&quot;6&quot;&gt;&lt;/rect&gt;&lt;g id=&quot;编组&quot; transform=&quot;translate(15.000000, 9.000000)&quot; fill=&quot;#FFFFFF&quot; fill-opacity=&quot;0.88&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;rect id=&quot;矩 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;180px&quot; height=&quot;173px&quot; viewBox=&quot;0 0 180 173&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;path d=&quot;M5.1277704,-1.1140022e-15 L138.87223,2.07168062e-16 C140.655267,-1.2037061e-16 141.30184,0.185651222 141.953691,0.534265408 C142.605543,0.882879593 143.11712,1.39445674 143.465735,2.04630859 C143.814349,2.69816044 144,3.34473292 144,5.1277704 L144,131.87223 C144,133.655267 143.814349,134.30184 143.465735,134.953691 C143.11712,135.605543 142.605543,136.11712 141.953691,136.465735 C141.30184,136.8 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;180px&quot; height=&quot;90px&quot; viewBox=&quot;0 0 180 90&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-164.000000, -3257.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Carousel&quot; transform=&quot;translate(164.000000, 3257.000000)&quot;&gt;&lt;path d=&quot;M6,0 L174,0 C177.313708,-6.08718376e-16 180,2.6862915 180,6 L180,84 C180,87.3137085 177.313708,90 174,90 L6,90 C2.6862915,90 -4.82366169e-16,87.3137085 0,84 L0,6 C-4.05812251e- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; width=&quot;140&quot; height=&quot;140&quot;&gt;&lt;path d=&quot;M428.501333 64a64 64 0 0 1 64 64v42.666667a64 64 0 0 1-64 64H128A64 64 0 0 1 64 170.666667V128A64 64 0 0 1 128 64h300.501333z&quot; fill=&quot;#29C287&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M896 305.92a64 64 0 0 1 64 64v42.666667a64 64 0 0 1-64 64H128a64 64 0 0 1-64-64v-42.666667A64 64 0 0 1 128 305.92h768z&quot; fill=&quot;#706EE7&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M584.362667 547.413333a64 64 0 0 1 64 64v42.666667a64 64 0 0 1-64 64H128a64 64 0 0 1-64-64v-42.666667a64 64 0 0 1 64-64h456.362667z&quot; fill=&quot;# [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;104px&quot; height=&quot;75px&quot; viewBox=&quot;0 0 104 75&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-931.000000, -1722.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;CheckBox&quot; transform=&quot;translate(932.000000, 1722.000000)&quot;&gt;&lt;g id=&quot;7.Icon/control/checkbox/Checked-&quot;&gt;&lt;g id=&quot;icon/z/checkboxChecked-Copy&quot; fill=&quot;#1677FF&quot;&gt;&lt;rect id=&quot;box&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;14&quot; height=&quot;14&quot; rx=&quot;2&quot;&gt;&lt;/rect&gt;&lt;/g&gt;&lt;g id=&quot;check&quot; transform=&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;150px&quot; height=&quot;102px&quot; viewBox=&quot;0 0 150 102&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-543.000000, -3247.000000)&quot;&gt;&lt;g id=&quot;Collapse&quot; transform=&quot;translate(543.000000, 3247.000000)&quot;&gt;&lt;path d=&quot;M2,0 L148,0 C149.104569,0 150,0.8954305 150,2 L150,24 L150,24 L0,24 L0,2 C0,0.8954305 0.8954305,0 2,0 Z&quot; id=&quot;矩形&quot; fill=&quot;#F5F5F5&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;/path&gt;&lt;path d=&quot;M0,78 L150,78 L150,100 C150,10 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;157px&quot; height=&quot;138px&quot; viewBox=&quot;0 0 157 138&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;linearGradient x1=&quot;100%&quot; y1=&quot;50%&quot; x2=&quot;0%&quot; y2=&quot;50%&quot; id=&quot;linearGradient-1&quot;&gt;&lt;stop stop-color=&quot;#1677FF&quot; offset=&quot;0%&quot;&gt;&lt;/stop&gt;&lt;stop stop-color=&quot;#FFFFFF&quot; offset=&quot;100%&quot;&gt;&lt;/stop&gt;&lt;/linearGradient&gt;&lt;linearGradient x1=&quot;50%&quot; y1=&quot;0.0897381757%&quot; x2=&quot;50%&quot; y2=&quot;100%&quot; id=&quot;linearGradient-2&quot;&gt;&lt;stop stop-color=&quot;#000000&quot; stop-opacity=&quot;0&quot; offset=&quot;0.0897381757%&quot;&gt;&lt;/stop&gt;&lt;stop stop-color=&quot;#000000&quot; offset=&quot;100%&quot;&gt;&lt;/stop&gt;&lt;/linearGradien [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;121px&quot; height=&quot;69px&quot; viewBox=&quot;0 0 121 69&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-1286.000000, -1724.000000)&quot;&gt;&lt;g id=&quot;编组-4&quot; transform=&quot;translate(1287.000000, 1725.000000)&quot;&gt;&lt;g id=&quot;Z/Shape/RectangleRC/2px/RC-A&quot;&gt;&lt;rect id=&quot;BG/fill&quot; fill=&quot;#FFFFFF&quot; fill-rule=&quot;nonzero&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;118&quot; height=&quot;30&quot; rx=&quot;1&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;outline&quot; stroke=&quot;#000000&quot; opacity=&quot;0.15&quot;  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;155px&quot; height=&quot;101px&quot; viewBox=&quot;0 0 155 101&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-176.000000, -775.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Divider&quot; transform=&quot;translate(176.000000, 775.000000)&quot;&gt;&lt;rect id=&quot;矩形复制-81&quot; fill=&quot;#F5F5F5&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;150&quot; height=&quot;6&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-85&quot; fill=&quot;#F5F5F5&quot; x=&quot;0&quot; y=&quot;67&quot; width=&quot;150&quot; height=&quot;6&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-82&quot; fill=&quot;#F5F5F5&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Divider {
            get {
                return ResourceManager.GetString("Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;161px&quot; height=&quot;117px&quot; viewBox=&quot;0 0 161 117&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-537.000000, -4310.000000)&quot;&gt;&lt;g id=&quot;O1CN019djdZP1OHwXSRGCOW_!!6000000001681-55-tps-161-117&quot; transform=&quot;translate(537.000000, 4310.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#EEEEEE&quot; fill-rule=&quot;nonzero&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;160.926&quot; height=&quot;117&quot; rx=&quot;2&quot;&gt;&lt;/rect&gt;&lt;polygon id=&quot;路径&quot; fill=&quot;#FFFFFF&quot; fill-rule= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Drawer {
            get {
                return ResourceManager.GetString("Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;120px&quot; height=&quot;93px&quot; viewBox=&quot;0 0 120 93&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-922.000000, -1129.000000)&quot;&gt;&lt;g id=&quot;Dropdown&quot; transform=&quot;translate(922.000000, 1129.000000)&quot;&gt;&lt;g id=&quot;Navigation/DropdownMenu&quot; transform=&quot;translate(0.000000, 21.500000)&quot;&gt;&lt;g id=&quot;Z/Shape/RectangleRC/2px/RC-A&quot; transform=&quot;translate(0.500000, 0.000000)&quot;&gt;&lt;rect id=&quot;BG/fill&quot; fill=&quot;#FFFFFF&quot; fill-r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;232px&quot; height=&quot;128px&quot; viewBox=&quot;0 0 232 128&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;rect id=&quot;path-1&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;232&quot; height=&quot;128&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;path-3&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;232&quot; height=&quot;128&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;path-5&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;232&quot; height=&quot;128&quot;&gt;&lt;/rect&gt;&lt;/defs&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-867.000000, -5129.000000)&quot;&gt;&lt;g id=&quot;9b1b62fe-e677-4afc-b9fe-1b2993662611&quot; transform=&quot;t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FloatButton {
            get {
                return ResourceManager.GetString("FloatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;156px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 156 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-540.000000, -775.000000)&quot;&gt;&lt;g id=&quot;Grid&quot; transform=&quot;translate(541.000000, 775.000000)&quot;&gt;&lt;g id=&quot;编组-27&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#F5F5F5&quot; fill-rule=&quot;nonzero&quot; x=&quot;9.8333333&quot; y=&quot;0&quot; width=&quot;10.3333333&quot; height=&quot;104&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-9&quot; fill=&quot;#F5F5F5&quot; fill-rule=&quot;nonzero&quot; x=&quot;51.1666667&quot; y=&quot;0&quot; width=&quot;10.333 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;150px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 150 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-907.000000, -427.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Typography&quot; transform=&quot;translate(907.000000, 427.000000)&quot;&gt;&lt;rect id=&quot;矩形复制-90&quot; fill=&quot;#F5F5F5&quot; x=&quot;6&quot; y=&quot;6.5&quot; width=&quot;137&quot; height=&quot;90&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#E0E0E0&quot; x=&quot;0&quot; y=&quot;18.5&quot; width=&quot;150&quot; height=&quot;1&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-89&quot; fill=&quot;#E0E0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HyperlinkLabel {
            get {
                return ResourceManager.GetString("HyperlinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;112px&quot; height=&quot;32px&quot; viewBox=&quot;0 0 112 32&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-562.000000, -463.000000)&quot;&gt;&lt;g id=&quot;Icon&quot; transform=&quot;translate(562.000000, 463.000000)&quot;&gt;&lt;g id=&quot;smile-fill&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#000000&quot; fill-rule=&quot;nonzero&quot; opacity=&quot;0&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;32&quot; height=&quot;32&quot;&gt;&lt;/rect&gt;&lt;path d=&quot;M16,2 C8.26875,2 2,8.26875 2,16 C2,23.73125 8.26875,30 16,30 C23.73125,30 30,23. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;133px&quot; height=&quot;96px&quot; viewBox=&quot;0 0 133 96&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-185.000000, -3490.000000)&quot;&gt;&lt;g id=&quot;编组备份-5&quot; transform=&quot;translate(186.000000, 3491.000000)&quot;&gt;&lt;rect id=&quot;d&quot; stroke-opacity=&quot;0.15&quot; stroke=&quot;#000000&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;131&quot; height=&quot;94&quot;&gt;&lt;/rect&gt;&lt;polygon id=&quot;路径&quot; fill-opacity=&quot;0.15&quot; fill=&quot;#000000&quot; fill-rule=&quot;nonzero&quot; points=&quot;0 94 62.7424567 42.1146849 81.84 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;121px&quot; height=&quot;77px&quot; viewBox=&quot;0 0 121 77&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-558.000000, -1959.000000)&quot;&gt;&lt;g id=&quot;Input&quot; transform=&quot;translate(559.000000, 1960.000000)&quot;&gt;&lt;g id=&quot;3.DataEntry/Input/Default/Basic-#&quot;&gt;&lt;g id=&quot;Z/Shape/RectangleRC/2px/RC-A&quot;&gt;&lt;rect id=&quot;BG/fill&quot; fill=&quot;#FFFFFF&quot; fill-rule=&quot;nonzero&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;118&quot; height=&quot;30&quot; rx=&quot;1&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;outline&quot; st [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;121px&quot; height=&quot;34px&quot; viewBox=&quot;0 0 121 34&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;path d=&quot;M0,15 L21,15 L21,28.0081158 C21,29.1082031 20.0976562,30 19.0054385,30 L0,30 L0,15 Z&quot; id=&quot;path-1&quot;&gt;&lt;/path&gt;&lt;filter x=&quot;-2.4%&quot; y=&quot;-3.3%&quot; width=&quot;104.8%&quot; height=&quot;106.7%&quot; filterUnits=&quot;objectBoundingBox&quot; id=&quot;filter-2&quot;&gt;&lt;feOffset dx=&quot;1&quot; dy=&quot;0&quot; in=&quot;SourceAlpha&quot; result=&quot;shadowOffsetInner1&quot;&gt;&lt;/feOffset&gt;&lt;feComposite in=&quot;shadowOffsetInner1&quot; in2=&quot;SourceAlpha&quot; operator=&quot;arithmetic&quot; k2=&quot;-1&quot; k3=&quot;1&quot; result=&quot;shadowInne [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;80px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 80 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-1306.000000, -1121.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Menu&quot; transform=&quot;translate(1306.000000, 1121.000000)&quot;&gt;&lt;rect id=&quot;矩形复制-41&quot; fill=&quot;#F5F5F5&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;80&quot; height=&quot;104&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#BAE0FF&quot; x=&quot;3&quot; y=&quot;29&quot; width=&quot;74&quot; height=&quot;22&quot; rx=&quot;4&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-51&quot; fill=&quot;#EBEBE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;154px&quot; height=&quot;42px&quot; viewBox=&quot;0 0 154 42&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-907.000000, -4341.000000)&quot;&gt;&lt;g id=&quot;Feedback/Message/Light/Success&quot; transform=&quot;translate(908.000000, 4342.000000)&quot;&gt;&lt;path d=&quot;M10.2555408,-2.76224082e-16 L141.744459,4.14336123e-16 C145.310534,-2.4074122e-16 146.603679,0.371302445 147.907383,1.06853082 C149.211087,1.76575919 150.234241,2. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;208px&quot; height=&quot;102px&quot; viewBox=&quot;0 0 208 102&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-1243.000000, -4311.000000)&quot;&gt;&lt;g id=&quot;Feedback/Modal/Light/Basic备份&quot; transform=&quot;translate(1244.000000, 4312.000000)&quot;&gt;&lt;path d=&quot;M6.15332448,2.8768262e-16 L199.846676,2.48601674e-16 C201.98632,-1.44444732e-16 202.762207,0.222781467 203.54443,0.641118489 C204.326652,1.05945551 204.940544,1. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Modal {
            get {
                return ResourceManager.GetString("Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;186px&quot; height=&quot;60px&quot; viewBox=&quot;0 0 186 60&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-164.000000, -4572.000000)&quot;&gt;&lt;g id=&quot;Feedback/Modal/Light/Confirm备份&quot; transform=&quot;translate(165.000000, 4573.000000)&quot;&gt;&lt;path d=&quot;M6.15332472,2.87682614e-16 L177.846675,2.48601684e-16 C179.98632,-1.44444737e-16 180.762207,0.222781476 181.54443,0.641118515 C182.326652,1.05945555 182.940544,1.6 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;150px&quot; height=&quot;44px&quot; viewBox=&quot;0 0 150 44&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;页面-1&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;Popconfirm备份&quot; transform=&quot;translate(-208.000000, -48.000000)&quot;&gt;&lt;g id=&quot;PageHeader&quot; transform=&quot;translate(208.000000, 48.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; stroke=&quot;#D9D9D9&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;149&quot; height=&quot;43&quot; rx=&quot;2&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#D9D9D9&quot; x=&quot;48&quot; y=&quot;14&quot; width=&quot;1&quot; height=&quot;16&quot;&gt;&lt;/rect&gt;&lt;g id=&quot;arrowleft&quot; opacity=&quot;0.65&quot; transform=&quot;transl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;196px&quot; height=&quot;22px&quot; viewBox=&quot;0 0 196 22&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-155.000000, -1393.000000)&quot;&gt;&lt;g id=&quot;Small-1&quot; transform=&quot;translate(152.000000, 1393.000000)&quot;&gt;&lt;g id=&quot;1&quot; transform=&quot;translate(30.000000, 0.000000)&quot;&gt;&lt;rect id=&quot;框&quot; stroke=&quot;#1677FF&quot; fill=&quot;#FFFFFF&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;21&quot; height=&quot;21&quot; rx=&quot;4&quot;&gt;&lt;/rect&gt;&lt;text font-family=&quot;PingFangSC-Regular, PingFang SC&quot; fon [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;173px&quot; height=&quot;122px&quot; viewBox=&quot;0 0 173 122&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-1261.000000, -3003.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Card&quot; transform=&quot;translate(1262.000000, 3004.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; stroke=&quot;#F0F0F0&quot; fill=&quot;#FFFFFF&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;171&quot; height=&quot;120&quot; rx=&quot;4&quot;&gt;&lt;/rect&gt;&lt;polygon id=&quot;Rectangle-10&quot; fill-opacity=&quot;0.09&quot; fill=&quot;#000000&quot; points=&quot;0 38.82 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;174px&quot; height=&quot;97px&quot; viewBox=&quot;0 0 174 97&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-898.000000, -3491.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;4.数据展示/2.Popover气泡卡片/亮色/上左⬇️&quot; transform=&quot;translate(899.000000, 3492.000000)&quot;&gt;&lt;path d=&quot;M32.6568542,88 C31.5959883,88 30.5785726,88.4214274 29.8284271,89.1715729 L24.4142136,94.5857864 C23.633165,95.366835 22.366835,95.366835 21.5857 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Popover {
            get {
                return ResourceManager.GetString("Popover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;75px&quot; height=&quot;74px&quot; viewBox=&quot;0 0 75 74&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-945.000000, -4572.000000)&quot;&gt;&lt;g id=&quot;编组-3&quot; transform=&quot;translate(945.000000, 4572.000000)&quot;&gt;&lt;g id=&quot;Feedback/Progress/Light/Bar-Default-Mini&quot;&gt;&lt;g id=&quot;Progress&quot; transform=&quot;translate(0.000000, 4.540816)&quot;&gt;&lt;rect id=&quot;Progress-Bg&quot; fill-opacity=&quot;0.04&quot; fill=&quot;#000000&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;50&quot; height=&quot;3&quot; rx=&quot;1.5&quot;&gt;&lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 94 80&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-206.000000, -2198.000000)&quot;&gt;&lt;g id=&quot;编组-4&quot; transform=&quot;translate(207.000000, 2198.000000)&quot;&gt;&lt;g id=&quot;Icon/Radio-Selected&quot; transform=&quot;translate(0.000000, 2.000000)&quot;&gt;&lt;g id=&quot;save&quot;&gt;&lt;/g&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#000000&quot; fill-rule=&quot;nonzero&quot; opacity=&quot;0&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;16&quot; height=&quot;16&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;Rectangle-271&quot; fill=&quot;#1677FF&quot; x=&quot;0&quot; y= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;180px&quot; height=&quot;24px&quot; viewBox=&quot;0 0 180 24&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-517.000000, -2225.000000)&quot;&gt;&lt;g id=&quot;DataEntry/Rate/Light/Default&quot; transform=&quot;translate(517.000000, 2225.000000)&quot;&gt;&lt;text id=&quot;Text&quot; font-family=&quot;PingFangSC-Regular, PingFang SC&quot; font-size=&quot;14&quot; font-weight=&quot;normal&quot; line-spacing=&quot;22&quot; fill=&quot;#000000&quot; fill-opacity=&quot;0.88&quot;&gt;&lt;tspan x=&quot;159&quot; y=&quot;16&quot;&gt;3.5&lt;/tspan&gt;&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;137px&quot; height=&quot;117px&quot; viewBox=&quot;0 0 137 117&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-1279.000000, -4547.000000)&quot;&gt;&lt;g id=&quot;Result&quot; transform=&quot;translate(1279.000000, 4547.000000)&quot;&gt;&lt;g id=&quot;1.通用/2.Icon图标/Fill/Check-Circle-Fill&quot; transform=&quot;translate(46.000000, 0.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#000000&quot; fill-rule=&quot;nonzero&quot; opacity=&quot;0&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;44.7457627&quot; height=&quot;44.7457627&quot;&gt;&lt;/r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;192px&quot; height=&quot;44px&quot; viewBox=&quot;0 0 192 44&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-1233.000000, -3518.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;a3ff040f-24ba-43e0-92e9-c845df1612ad-(1)&quot; transform=&quot;translate(1233.000000, 3518.000000)&quot;&gt;&lt;path d=&quot;M5.1277704,0 L186.87223,0 C188.655267,0 189.30184,0.185651222 189.953691,0.534265408 C190.605543,0.882879593 191.11712,1.39445674 1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Segmented {
            get {
                return ResourceManager.GetString("Segmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;121px&quot; height=&quot;33px&quot; viewBox=&quot;0 0 121 33&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-923.000000, -2221.000000)&quot;&gt;&lt;g id=&quot;3.DataEntry/Selecte/Default/Unselected&quot; transform=&quot;translate(924.000000, 2222.000000)&quot;&gt;&lt;rect id=&quot;outline&quot; stroke=&quot;#000000&quot; opacity=&quot;0.15&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;119&quot; height=&quot;31&quot; rx=&quot;6&quot;&gt;&lt;/rect&gt;&lt;g id=&quot;编组备份-66&quot; transform=&quot;translate(12.000000, 8.000000)&quot; fill [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 0 929 545&quot; width=&quot;140&quot; height=&quot;140&quot;&gt;&lt;path fill=&quot;#53C71B&quot; transform=&quot;scale(4.26092 4.26092)&quot; d=&quot;M164.953 13.3737C168.355 13.113 171.945 13.4596 175.243 14.3272C178.834 15.2718 187.295 19.0877 189.186 22.3315C189.181 22.4175 189.17 22.4997 189.149 22.5836C188.887 23.6306 185.526 27.2296 184.587 27.8441C184.528 27.613 184.448 27.3818 184.292 27.1966C180.744 22.9809 173.794 20.7053 168.481 20.3731C163.384 19.6188 156.976 21.8564 152.87 24.8118C151.652 2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Singal {
            get {
                return ResourceManager.GetString("Singal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;150px&quot; height=&quot;14px&quot; viewBox=&quot;0 0 150 14&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-1270.000000, -2228.000000)&quot;&gt;&lt;g id=&quot;Silder&quot; transform=&quot;translate(1270.000000, 2228.000000)&quot;&gt;&lt;rect id=&quot;Rectangle-20&quot; fill-opacity=&quot;0.04&quot; fill=&quot;#000000&quot; x=&quot;0&quot; y=&quot;5&quot; width=&quot;150&quot; height=&quot;4&quot; rx=&quot;2&quot;&gt;&lt;/rect&gt;&lt;path d=&quot;M1,7 C1,5.8954305 1.89453347,5 3.00606883,5 L73.9939312,5 C75.1018524,5 76,5.88772964 76 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;-8 -8 40 40&quot; width=&quot;100&quot; height=&quot;100&quot;&gt;&lt;path fill=&quot;#000000&quot; d=&quot;M12 4.5a7.5 7.5 0 1 0 0 15a7.5 7.5 0 0 0 0-15M1.5 12C1.5 6.201 6.201 1.5 12 1.5S22.5 6.201 22.5 12S17.799 22.5 12 22.5S1.5 17.799 1.5 12&quot; fill-opacity=&quot;.1&quot;/&gt;&lt;path fill=&quot;#1677ff&quot; d=&quot;M12 4.5a7.46 7.46 0 0 0-5.187 2.083a1.5 1.5 0 0 1-2.075-2.166A10.46 10.46 0 0 1 12 1.5a1.5 1.5 0 0 1 0 3&quot;/&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Spin {
            get {
                return ResourceManager.GetString("Spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;160&quot; height=&quot;112&quot; viewBox=&quot;0 0 160 112&quot; fill=&quot;none&quot;&gt;&lt;rect width=&quot;160&quot; height=&quot;112&quot; rx=&quot;4&quot; fill=&quot;#1668DC&quot; fill-opacity=&quot;0.1&quot;/&gt;&lt;path d=&quot;M10 12C10 10.8954 10.8954 10 12 10H56V102H12C10.8954 102 10 101.105 10 100V12Z&quot; fill=&quot;#fff&quot;/&gt;&lt;rect x=&quot;57&quot; y=&quot;10&quot; width=&quot;46&quot; height=&quot;92&quot; fill=&quot;#fff&quot;/&gt;&lt;path d=&quot;M104 10H148C149.105 10 150 10.8954 150 12V100C150 101.105 149.105 102 148 102H104V10Z&quot; fill=&quot;#fff&quot;/&gt;&lt;path d=&quot;M55.625 49H57.375V63H55.625V49ZM52.125 53.375L49.5 56L52.125 58.625V56.875H54.75V55.125H52.125V53.3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Splitter {
            get {
                return ResourceManager.GetString("Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;108px&quot; height=&quot;116px&quot; viewBox=&quot;0 0 108 116&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-566.000000, -1360.000000)&quot;&gt;&lt;g id=&quot;小-垂直-带描述&quot; transform=&quot;translate(566.000000, 1361.000000)&quot;&gt;&lt;g id=&quot;导航/Steps步骤条/Light/小-垂直-带描述-完成项&quot; transform=&quot;translate(0.000000, -0.600000)&quot;&gt;&lt;text id=&quot;Finished&quot; font-family=&quot;PingFangSC-Regular, PingFang SC&quot; font-size=&quot;9.6&quot; font-weight=&quot;normal&quot; line-spacing=&quot;14.4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;160px&quot; height=&quot;16px&quot; viewBox=&quot;0 0 160 16&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-174.000000, -2473.000000)&quot;&gt;&lt;g id=&quot;编组-5&quot; transform=&quot;translate(174.000000, 2473.000000)&quot;&gt;&lt;g id=&quot;DataEntry/Switch/Light/Small-On&quot;&gt;&lt;path d=&quot;M0,8 L0,8 C0,3.581722 3.57465974,0 8.00493448,0 L19.9950655,0 C24.4160688,0 28,3.59071231 28,8 L28,8 C28,12.418278 24.4253403,16 19.9950655,16 L8.00493448,16 C3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;155px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 155 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-541.000000, -3726.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Table&quot; transform=&quot;translate(541.000000, 3726.000000)&quot;&gt;&lt;rect id=&quot;矩形复制-55&quot; fill=&quot;#EBEBEB&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;155&quot; height=&quot;20&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-81&quot; fill=&quot;#EBEBEB&quot; x=&quot;11&quot; y=&quot;32&quot; width=&quot;23&quot; height=&quot;6&quot;&gt;&lt;/rect&gt;&lt;rect id=&quot;矩形复制-155&quot; fill=&quot;#EBEBE [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;208px&quot; height=&quot;32px&quot; viewBox=&quot;0 0 208 32&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-879.000000, -3762.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Tabs&quot; transform=&quot;translate(879.000000, 3762.000000)&quot;&gt;&lt;g id=&quot;编组&quot; transform=&quot;translate(85.000000, 0.000000)&quot; fill=&quot;#000000&quot; fill-opacity=&quot;0.85&quot; font-family=&quot;PingFangSC-Regular, PingFang SC&quot; font-size=&quot;14&quot; font-weight=&quot;normal&quot;&gt;&lt;text id=&quot;Tab-2&quot;&gt;&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tabs {
            get {
                return ResourceManager.GetString("Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;193px&quot; height=&quot;57px&quot; viewBox=&quot;0 0 193 57&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-1251.000000, -3750.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Tag&quot; transform=&quot;translate(1252.000000, 3751.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; stroke=&quot;#D9D9D9&quot; fill=&quot;#FAFAFA&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;46&quot; height=&quot;21&quot; rx=&quot;2&quot;&gt;&lt;/rect&gt;&lt;text id=&quot;Tag-1&quot; font-family=&quot;PingFangSC-Regular, PingFang SC&quot; font-size=&quot;12&quot; font-weight=&quot;no [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;168px&quot; height=&quot;103px&quot; viewBox=&quot;0 0 168 103&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-170.000000, -3969.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;Timeline&quot; transform=&quot;translate(171.000000, 3969.000000)&quot;&gt;&lt;rect id=&quot;矩形&quot; fill=&quot;#E9E9E9&quot; x=&quot;2.24&quot; y=&quot;1.5&quot; width=&quot;1.494&quot; height=&quot;99.771&quot; rx=&quot;0.747&quot;&gt;&lt;/rect&gt;&lt;path d=&quot;M13.885,101.812 L13.885,98.595 L16.198,98.595 C16.613,98.595 16.918,98.641 17.11 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;121px&quot; height=&quot;69px&quot; viewBox=&quot;0 0 121 69&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版&quot; transform=&quot;translate(-557.000000, -2446.000000)&quot;&gt;&lt;g id=&quot;TimePicker&quot; transform=&quot;translate(558.000000, 2447.000000)&quot;&gt;&lt;g id=&quot;3.DataEntry/Selecte/Default/Unselected&quot;&gt;&lt;g id=&quot;3.DataEntry/Input/Default/Basic-#&quot;&gt;&lt;g id=&quot;9.Box/1.Cards/4.Border&quot; opacity=&quot;0.15&quot; stroke=&quot;#000000&quot;&gt;&lt;g id=&quot;Z/Shape/RectangleRC/2px/RC-A&quot;&gt;&lt;rect id=&quot;outl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TimePicker {
            get {
                return ResourceManager.GetString("TimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;118px&quot; height=&quot;38px&quot; viewBox=&quot;0 0 118 38&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-560.000000, -3994.000000)&quot;&gt;&lt;g id=&quot;编组备份-48&quot; transform=&quot;translate(448.000000, 3894.000000)&quot; fill=&quot;#FFFFFF&quot; stroke=&quot;#000000&quot; stroke-opacity=&quot;0.08&quot;&gt;&lt;rect id=&quot;矩形&quot; x=&quot;0.5&quot; y=&quot;0.5&quot; width=&quot;339&quot; height=&quot;215&quot; rx=&quot;8&quot;&gt;&lt;/rect&gt;&lt;/g&gt;&lt;g id=&quot;DataDisplay/Tooltip/Light/Down⬇️&quot; transform=&quot;translate(560.00 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;175px&quot; height=&quot;104px&quot; viewBox=&quot;0 0 175 104&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-896.000000, -3968.000000)&quot; fill-rule=&quot;nonzero&quot;&gt;&lt;g id=&quot;cc3fcbfa-bf5b-4c8c-8a3d-c3f8388c75e8&quot; transform=&quot;translate(897.000000, 3969.000000)&quot;&gt;&lt;path d=&quot;M27.3015827,0.481523055 C27.3793404,0.54817244 27.4518638,0.620695897 27.5185132,0.698453513 L30.0476259,3.64908497 C30.1294246,3.74451 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;196px&quot; height=&quot;116px&quot; viewBox=&quot;0 0 196 116&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;path d=&quot;M5.84,3.5 L2.16,3.5 C2.0715,3.5 2,3.517875 2,3.54 L2,4.46 C2,4.482125 2.0715,4.5 2.16,4.5 L5.84,4.5 C5.9285,4.5 6,4.482125 6,4.46 L6,3.54 C6,3.517875 5.9285,3.5 5.84,3.5 Z&quot; id=&quot;path-1&quot;&gt;&lt;/path&gt;&lt;/defs&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-885.000000, -2421.000000)&quot;&gt;&lt;g id=&quot;编组-6&quot; transform=&quot;translate(885.0000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;89px&quot; height=&quot;85px&quot; viewBox=&quot;0 0 89 85&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;g id=&quot;组件骨架图更新_202311&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g id=&quot;🎉-5.0-新版---白&quot; transform=&quot;translate(-1302.000000, -3977.000000)&quot;&gt;&lt;g id=&quot;编组-8&quot; transform=&quot;translate(1302.000000, 3977.000000)&quot;&gt;&lt;g id=&quot;编组-12&quot; transform=&quot;translate(0.000000, 1.556962)&quot;&gt;&lt;rect id=&quot;矩形&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;9.11392405&quot; height=&quot;6.07594937&quot;&gt;&lt;/rect&gt;&lt;path d=&quot;M7.36230459,4.76344426 L4.61669573,1.58717625 C4.53810644,1.4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg width=&quot;196px&quot; height=&quot;118px&quot; viewBox=&quot;0 0 196 118&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;&lt;defs&gt;&lt;rect id=&quot;path-1&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;194&quot; height=&quot;116&quot; rx=&quot;6.4000001&quot;&gt;&lt;/rect&gt;&lt;/defs&gt;&lt;g stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;g transform=&quot;translate(-520.000000, -5480.000000)&quot;&gt;&lt;g transform=&quot;translate(521.000000, 5481.000000)&quot;&gt;&lt;mask id=&quot;mask-2&quot; fill=&quot;white&quot;&gt;&lt;use xlink:href=&quot;#path-1&quot;&gt;&lt;/use&gt;&lt;/mask&gt;&lt;use stroke=&quot;#F0F0F0&quot; stroke-width=&quot;0.8&quot; fill=&quot;#FFFFFF&quot; fill-rule=&quot;nonzero&quot; xlink:hre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
    }
}
