//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Overview.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Overview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M137.6 262.144a52.8 52.8 0 0 1 4.608-5.632l0.064-0.128 168.64-177.472a46.528 46.528 0 0 1 68.48 0.256c17.088 18.24 18.56 46.784 4.48 66.816l-4.736 5.76-85.312 89.728h231.04C728.704 241.536 896 401.152 896 600.832c0 194.816-159.168 351.424-356.352 358.976L524.8 960H176.448C149.696 960 128 937.024 128 908.672c0-25.984 18.24-47.424 41.856-50.816l6.592-0.512H524.8c152.576 0 274.368-116.16 274.368-256.64 0-136.128-114.496-249.472-260.544-256.256L524.8 344.128H174.528a45.952  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string app_back {
            get {
                return ResourceManager.GetString("app_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M186.86 493.94h-70.39c-10.79 0-19.42 8.63-19.42 19.42 0 10.79 8.63 19.42 19.42 19.42h70.39c10.79 0 19.42-8.63 19.42-19.42 0-10.79-8.63-19.42-19.42-19.42z m77.86-200.71c7.47 7.47 19.59 7.47 27.39 0 7.47-7.8 7.47-19.92 0-27.39l-45.98-45.98c-7.8-7.8-19.92-7.8-27.39 0-7.8 7.47-7.8 19.76 0 27.39-0.01 0 45.98 45.98 45.98 45.98z m5.64 434.62l-51.63 51.63c-7.8 7.47-7.8 19.59 0 27.39 7.47 7.47 19.76 7.47 27.39 0l51.63-51.63c7.47-7.8 7.47-19.92 0-27.39-7.47-7.81-19.92-7.81-27.39  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string app_dark {
            get {
                return ResourceManager.GetString("app_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M186.86 493.94h-70.39c-10.79 0-19.42 8.63-19.42 19.42 0 10.79 8.63 19.42 19.42 19.42h70.39c10.79 0 19.42-8.63 19.42-19.42 0-10.79-8.63-19.42-19.42-19.42zM264.72 293.23c7.47 7.47 19.59 7.47 27.39 0 7.47-7.8 7.47-19.92 0-27.39l-45.98-45.98c-7.8-7.8-19.92-7.8-27.39 0-7.8 7.47-7.8 19.76 0 27.39-0.01 0 45.98 45.98 45.98 45.98zM270.36 727.85l-51.63 51.63c-7.8 7.47-7.8 19.59 0 27.39 7.47 7.47 19.76 7.47 27.39 0l51.63-51.63c7.47-7.8 7.47-19.92 0-27.39-7.47-7.81-19.92-7.81-27.39 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string app_light {
            get {
                return ResourceManager.GetString("app_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg2 {
            get {
                object obj = ResourceManager.GetObject("bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg3 {
            get {
                object obj = ResourceManager.GetObject("bg3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg4 {
            get {
                object obj = ResourceManager.GetObject("bg4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg5 {
            get {
                object obj = ResourceManager.GetObject("bg5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg6 {
            get {
                object obj = ResourceManager.GetObject("bg6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg7 {
            get {
                object obj = ResourceManager.GetObject("bg7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M923 283.6c-13.4-31.1-32.6-58.9-56.9-82.8-24.3-23.8-52.5-42.4-84-55.5-32.5-13.5-66.9-20.3-102.4-20.3-49.3 0-97.4 13.5-139.2 39-10 6.1-19.5 12.8-28.5 20.1-9-7.3-18.5-14-28.5-20.1-41.8-25.5-89.9-39-139.2-39-35.5 0-69.9 6.8-102.4 20.3-31.4 13-59.7 31.7-84 55.5-24.4 23.9-43.5 51.7-56.9 82.8-13.9 32.3-21 66.6-21 101.9 0 33.3 6.8 68 20.3 103.3 11.3 29.5 27.5 60.1 48.2 91 32.8 48.9 77.9 99.9 133.9 151.6 92.8 85.7 184.7 144.9 188.6 147.3l23.7 15.2c10.5 6.7 24 6.7 34.5 0l23.7-15 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string icon_like {
            get {
                return ResourceManager.GetString("icon_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot;&gt;&lt;path d=&quot;M372.134088 1004.846981a509.94041 509.94041 0 0 1-159.298198-76.821527l2.164315-103.514738a93.088793 93.088793 0 0 0-74.238313-93.088794l-101.536602-20.991523A509.428422 509.428422 0 0 1 0.011636 537.983409l82.243949-62.834935a93.088793 93.088793 0 0 0 26.507034-116.104998l-46.89348-92.390627A514.152678 514.152678 0 0 1 172.225904 128.415991l100.419536 25.133974a93.088793 93.088793 0 0 0 107.284834-51.664281l43.007023-94.252403a515.246472 515.246472 0 0 1 88.434354-7.61 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
    }
}
