name: BUG
description: Report an issue that affects running application
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        :warning: Have checked existing issues to see whether someone else has already reported your issue?
        :book: Please also read [Document](https://github.com/AntdUI/AntdUI/blob/main/doc/wiki/en/Home.md).

  - type: input
    attributes:
      label: Version
      description: Please enter the version number you are using.
      placeholder: E.g. 1.0.5, or daily Commit ID
    validations:
      required: true
  - type: textarea
    attributes:
      label: .NET version
      description: What is the version of .NET, use `dotnet --info`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: OS
      description: E.g. Windows 11, Operating system type and version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide step by step guide to repro this issue. In case repro steps are complex, it would be helpful if you attach a GIF with repro actions. Attaching a sample app to repro the issue will help us investigate.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: |
        Be as specific and detailed as possible to help us triaging your issue. Screenshots and/or animations can be very useful in helping to understand the issue you're facing.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        Tip: You can use https://www.screentogif.com/ to record animations and videos.
  - type: markdown
    attributes:
      value: |
        🙏 I promise to communicate with mutual respect, understanding, and friendliness to jointly maintain a good community atmosphere.