name: 问题反馈
description: 当你中发现了一个 Bug，导致应用崩溃或抛出异常，或者有一个组件存在问题，或者某些地方看起来不对劲。
labels: ["BUG"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ 请**明确指出**问题复现流程，以减少维护者在排查问题上浪费过多时间，并且仔细观看完 [文档📖](https://gitee.com/antdui/AntdUI/wikis) 后再提。
  - type: input
    attributes:
      label: 版本号
      description: 请输入您使用的版本号。
      placeholder: 例如：1.0.5，请不要填写“最新”等干扰描述，源码可填写提交id
    validations:
      required: true
  - type: dropdown
    id: net_sdk
    attributes:
      label: .NET SDK
      description: 请选择项目使用的 .NET SDK 版本？
      options:
        - .NET Framework 40
        - .NET Framework 45 以上
        - .NET Core 3.1
        - .NET6
        - .NET7
        - .NET8
        - .NET9
    validations:
      required: true
  - type: dropdown
    id: os_type
    attributes:
      label: 操作系统
      description: 请选择操作系统类型？
      options:
        - Windows 11
        - Windows 10
        - Windows 8
        - Windows 7
        - Windows XP
        - 其他
    validations:
      required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 异常信息
      description: 如果有异常请把详细异常堆栈粘贴上来。
  - type: textarea
    attributes:
      label: 截图或视频
      description: 如果可以的话，上传任何关于 bug 的截图。
      placeholder: |
        可在此处进行图片粘贴上传。
  - type: input
    id: demo
    attributes:
      label: Demo 地址（Git/网盘/SVN）
      description: 请提供复现错误的 Demo 下载
      placeholder: https://github.com/your_id/your_test_project.git
  - type: markdown
    attributes:
      value: |
        🙏 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护好良好的社区氛围。