name: 使用疑问
description: 当你不明白某个功能如何使用时，可以提交该Issue。
labels: ["问题"]
assignees: []
body:
  - type: input
    attributes:
      label: 版本号
      description: 请输入您使用的版本号。
      placeholder: 例如：1.0.5
    validations:
      required: true
  - type: dropdown
    id: net_sdk
    attributes:
      label: .NET SDK
      description: 请选择项目使用的 .NET SDK 版本？
      options:
        - .NET Framework 40
        - .NET Framework 45 以上
        - .NET Core 3.1
        - .NET6
        - .NET7
        - .NET8
    validations:
      required: true
  - type: dropdown
    id: os_type
    attributes:
      label: 操作系统
      description: 请选择操作系统类型？
      options:
        - Windows 11
        - Windows 10
        - Windows 8
        - Windows 7
        - Windows XP
        - 其他
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你的需求是什么？
      description: 清晰并简洁地描述你希望发生的事情。
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过现有的问题 (https://github.com/AntdUI/AntdUI/issues)
          required: true
  - type: checkboxes
    attributes:
      label: 友好承诺
      options:
        - label: 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护好良好的社区氛围。
          required: true