//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntdUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntdUI.EmojiFluentFlat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 H4sIAAAAAAAACuy9y64tS3ae9yoTpY7dUDLuF4MkUGeeOliNdQC3VmN3BEOkKAKEJehCueGGOrbphkVTakiiBNA2IMi2DEMtwzZg6134AuYjGN//R2TOOWvXOtsQIIiWahfOypgZGRm3jBgxxj/+8Wd/8s/+q//o1//m7//O7fd/97f/znd/7T/7jZ+FW7jldMvpZ7ff/PW//p/8rb96+63f+NmPcRy99XGL8ajxPeajlj5u6Zg5hHiP+UhB6VxDiLeYjjpJk38mrt7qkXMf93yMoTvpmL2PWz5q45F8NH4vx0iUWI9Agf2IKrAdg7fPIxaS84iRyoSj3ecxKCfGI05+GXFXk//2sVNvqwlffnb7K7/7e7/3Gz/7CyH08t3Pf/ZrD81M7WhV1U3hCK2Pe5xHXk0ZLu1s5DjKQyfQKSmdb0vhSLGPe4pHPOtwS2nVXLVNyZ2hdqR6xPzQxtSOyYv7EdVBaRw5PvRQmkeIDx2YxhE1BrezEY9N/Xn7xfdP [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
    }
}
